name: GitHub Actions Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}


    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4

    #   - name: Setup Node
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: '20'

      # - uses: pnpm/action-setup@v3.0.0
      #   name: Install pnpm
      #   id: pnpm-install
      #   with:
      #     version: 8
      #     run_install: true

      # - name: Install dependencies
      #   run: pnpm install

      # - name: Type check
      #   run: pnpm typecheck

      # - name: Lint code
        # run: pnpm lint
